components:
  schemas:
    DocumentType:
      type: string
      enum:
        # to be adjusted
        - File
        - Publication
        - Experiment
        - Study
        - Dataset

    FacetOption:
      type: object
      properties:
        option:
          type: string
        count:
          type: integer
      required:
        - option
      additionalProperties: false

    FilterOption:
      properties:
        key:
          title: Key
          type: string
        value:
          title: Value
          type: string
      required:
        - key
        - value
      title: FilterOption
      type: object

    Facet:
      type: object
      properties:
        key:
          type: string
        options:
          type: array
          items:
            $ref: "#/components/schemas/FacetOption"
      required:
        - key
        - options
      additionalProperties: false

    SearchQuery:
      description: Represents the Search Query.
      properties:
        filters:
          type: array
          items:
            $ref: '#/components/schemas/FilterOption'
        query:
          title: Query
          type: string
      required:
        - query
      title: SearchQuery
      type: object

    SearchHit:
      type: object
      properties:
        document_type:
          $ref: "#/components/schemas/DocumentType"
        id:
          type: string
          description: ID of metadata document
        context:
          type: string
          description: |
            Optionally, give the context (metadata field or sentence)
            where the hit was found.
        content:
          type: object
      required:
        - document_type
        - id
      additionalProperties: false

    SearchResult:
      type: object
      properties:
        hits:
          type: array
          items:
            $ref: "#/components/schemas/SearchHit"
        facets:
          type: array
          items:
            $ref: "#/components/schemas/Facet"
      required:
        - hits
        - facets
      additionalProperties: false

info:
  title: Metadata Search API
  version: 0.1.0

openapi: 3.0.2

paths:
  /rpc/search:
    post:
      operationId: search
      summary: Search metadata catalog by keywords and filters
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchQuery"
        description: >-
          Search keywords and filters.
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SearchResult"
          description: Successful Response
