openapi: 3.0.3

info:
  title: Upload Controller Service
  version: 0.2.0

paths:
  /files/{file_id}:

    get:
      operationId: getFileMetadata
      description: Get file metadata including the current upload attempt.
      parameters:
        - name: file_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: File metadata including the current upload attempt
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FileMetadata"
        "403":
          description: |
            The user is not registered as a Data Submitter for the
            corresponding file.
        "404":
          description: The file with the given ID has not (yet) been registered for upload.
          
  /uploads:

    post:
      operationId: createUpload
      description: Initiate a new mutli-part upload.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UploadCreation"
      responses:
        "200":
          description: Details on the newly created upload.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadDetails"
        "400":
          description: |
            It is currently not possible to create a new upload for
            the file with the specified ID because another upload for that
            file already exists and has not been completed yet
            (its status is not "failed", "rejected", or "accepted").
        "403":
          description: |
            Either the user is not registered as a Data Submitter for the
            corresponding file.
            Or it is currently not possible to create a new upload for
            the file with the specified ID because:
              - a previous upload for that file was already accepted
              - another upload for that file is currently in progress Or
                is waiting for acceptance

  /uploads/{upload_id}:

    get:
      operationId: getUploadDetails
      description: Get details on a specific upload.
      parameters:
        - name: upload_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Details on a specific upload.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadDetails"
        "403":
          description: |
            Either the user is not registered as a Data Submitter for the
            file corresponding to this upload.
        "404":
          description: The upload with the given ID does not exist (anymore).

    patch:
      operationId: updateUploadStatus
      description: |
        Declare a multi-part upload as complete by setting its status to "uploaded".
        Or cancel a multi-part upload by setting its status to "cancelled".
      parameters:
        - name: upload_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UploadUpdate"
      responses:
        "204":
          description: Multi-part upload successfully updated.
        "403":
          description: |
            The user is not registered as a Data Submitter for the
            file corresponding to this multi-part upload.
        "404":
          description: The multi-part upload with the given ID does not exist.

  /uploads/{upload_id}/parts/{part_no}/signed_posts:
    post:
      operationId: createPreSignedPost
      description: |
        Create a pre-signed post for the specified part number of the specified multi-part
        upload.
      parameters:
        - name: upload_id
          in: path
          required: true
          schema:
            type: string
        - name: part_no
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 10000
      responses:
        "200":
          description: |
            The newly create pre-signed POST.
          content:
            application/json:
              schema:
                description: To be defined in further detail.
                type: object
        "403":
          description: |
            The user is not registered as a Data Submitter for the
            file corresponding to this multi-part upload.
        "404":
          description: The multi-part upload with the given ID does not exist.

components:
  schemas:
    UploadCreation:
      title: Properties required to create a new upload
      type: object
      properties:
        file_id:
          type: string
          description: The ID of the file corresponding to this upload.
      required:
        - upload_id


    UploadDetails:
      title: Multi-Part Upload Details
      type: object
      properties:
        upload_id:
          type: string
        file_id:
          type: string
          description: The ID of the file corresponding to this upload.
        part_size:
          type: integer
          description: Part size in bytes.
      required:
        - upload_id
        - file_id
        - part_size

    UploadUpdate:
      title: Multi-Part Upload Update
      type: object
      properties:
        status:
          type: string
          enum:
            - uploaded
            - cancelled

    FileMetadata:
      title: Multi-Part Upload Details
      type: object
      properties:
        file_id:
          type: string
        file_name:
          type: string
        md5_checksum:
          type: string
        size:
          type: integer
          minimum: 0
        grouping_label:
          type: string
        creation_date:
          type: string
          format: date-time
        update_date:
          type: string
          format: date-time
        format:
          type: string
        current_upload_id:
          description: |
            ID of the current upload. `Null` if no update has been
            initiated, yet.
          type: string
          nullable: true
      required:
        - file_id
        - file_name
        - md5_checksum
        - grouping_label
        - creation_date
        - update_date
        - format
        - current_upload_id
