openapi: 3.0.3

info:
  title: Upload Controller Service
  version: 0.2.0

paths:
  /files/{file_id}/uploads:
    post:
      operationId: createUpload
      description: Initiate a new mutli-part upload.
      parameters:
        - name: file_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Details on the newly created upload.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadDetails"
        "403":
          description: |
            Either the user is not registered as a Data Submitter for the
            corresponding file.
            Or it is currently not possible to create a new upload for
            the file with the specified ID because:
              - a previous upload for that file was already accepted
              - another upload for that file is currently in progress Or
                is waiting for acceptance
        "404":
          description: The file with the given ID has not (yet) been registered for upload.

    get:
      operationId: getPendingUploads
      description: |
        Get all multi-part uploads (can only be 1 or none) which are currently pending.
        E.g. this endpoint is useful if the client has lost the ID of the currently ongoing
        upload.
      parameters:
        - name: file_id
          in: path
          required: true
          schema:
            type: string
        - name: status
          in: query
          description: |
            The status of the multi-part upload, only "pending" is allowed as
            the single option.
          required: true
          schema:
            type: string
            enum: ["pending"]
      responses:
        "200":
          description: |
            List of pending multi-part uploads and their details.
            Please note, the list may either contain 1 or 0 elements.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UploadDetails"
        "403":
          description: |
            The user is not registered as a Data Submitter for the
            corresponding file.
        "404":
          description: The file with the given ID has not (yet) been registered for upload.

  /uploads/{upload_id}:
    patch:
      operationId: updateUploadStatus
      description: |
        Declare a multi-part upload as complete by setting its status to "uploaded".
        Or cancel a multi-part upload by setting its status to "cancelled".
      parameters:
        - name: upload_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UploadUpdate"
      responses:
        "204":
          description: Multi-part upload successfully updated.
        "403":
          description: |
            The user is not registered as a Data Submitter for the
            file corresponding to this multi-part upload.
        "404":
          description: The multi-part upload with the given ID does not exist.

  /uploads/{upload_id}/parts/{part_no}/signed_posts:
    post:
      operationId: createPreSignedPost
      description: |
        Create a pre-signed post for the specified part number of the specified multi-part
        upload.
      parameters:
        - name: upload_id
          in: path
          required: true
          schema:
            type: string
        - name: part_no
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 10000
      responses:
        "200":
          description: |
            The newly create pre-signed POST.
          content:
            application/json:
              schema:
                description: To be defined in further detail.
                type: object
        "403":
          description: |
            The user is not registered as a Data Submitter for the
            file corresponding to this multi-part upload.
        "404":
          description: The multi-part upload with the given ID does not exist.

components:
  schemas:
    UploadDetails:
      title: Multi-Part Upload Details
      type: object
      properties:
        upload_id:
          type: string
        part_size:
          type: integer
          description: Part size in bytes.
      required:
        - upload_id
        - part_size
    UploadUpdate:
      title: Multi-Part Upload Update
      type: object
      properties:
        status:
          type: string
          enum:
            - uploaded
            - cancelled
