info:
  title: Metadata Transpiler Service
  version: 0.1.0
openapi: 3.0.2
paths:
  /:
    get:
      description: 'Index of the Metadata Transpiler Service that redirects to the API documentation.'
      operationId: index__get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Index
  /convert:
    post:
      description: "Input XLSX and respond with Submission JSON"
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
