components:
  schemas:
    Dataset:
      properties:
        description:
          title: Description
          type: string
        files:
          items:
            type: string
          title: Files
          type: array
        has_study:
          title: Has Study
          type: string
        id:
          title: Id
          type: string
        title:
          title: Title
          type: string
        type:
          title: Type
          type: string
      required:
        - id
      title: Dataset
      type: object
    Experiment:
      properties:
        has_study:
          title: Has Study
          type: string
        id:
          title: Id
          type: string
        instrument_model:
          title: Instrument Model
          type: string
        name:
          title: Name
          type: string
      required:
        - id
      title: Experiment
      type: object
    File:
      properties:
        category:
          title: Category
          type: string
        checksum:
          title: Checksum
          type: string
        format:
          title: Format
          type: string
        id:
          title: Id
          type: string
        name:
          title: Name
          type: string
        size:
          title: Size
          type: string
        type:
          title: Type
          type: string
      required:
        - id
      title: File
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: "#/components/schemas/ValidationError"
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    Publication:
      properties:
        id:
          title: Id
          type: string
        title:
          title: Title
          type: string
      required:
        - id
      title: Publication
      type: object
    Study:
      properties:
        abstract:
          title: Abstract
          type: string
        id:
          title: Id
          type: string
        publications:
          items:
            type: string
          title: Publications
          type: array
        title:
          title: Title
          type: string
        type:
          title: Type
          type: string
      required:
        - id
      title: Study
      type: object
    ValidationError:
      properties:
        loc:
          items:
            type: string
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
        - loc
        - msg
        - type
      title: ValidationError
      type: object
info:
  title: Metadata Service API
  version: 0.1.0
openapi: 3.0.2
paths:
  /datasets:
    get:
      operationId: list_all_datasets_datasets_get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: string
                title: Response Get All Datasets Datasets Get
                type: array
          description: Successful Response
      summary: List all Dataset IDs
  /datasets/{dataset_id}:
    get:
      operationId: get_datasets_datasets_dataset_id
      parameters:
        - in: path
          name: dataset_id
          required: true
          schema:
            title: Dataset Id
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dataset"
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Get a specific Dataset
  /experiments:
    get:
      operationId: list_all_experiments_experiments_get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: string
                title: Response Get All Experiments Experiments Get
                type: array
          description: Successful Response
      summary: List all Experiment IDs
  /experiments/{experiment_id}:
    get:
      operationId: get_experiments_experiments_experiment_id
      parameters:
        - in: path
          name: experiment_id
          required: true
          schema:
            title: Experiment Id
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Experiment"
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Get a specific Experiment
  /files:
    get:
      operationId: list_all_files_files_get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: string
                title: Response Get All Files Files Get
                type: array
          description: Successful Response
      summary: List all File IDs
  /files/{file_id}:
    get:
      operationId: get_files_files_file_id
      parameters:
        - in: path
          name: file_id
          required: true
          schema:
            title: File Id
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/File"
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Get a specific File
  /publications:
    get:
      operationId: list_all_publications_publications_get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: string
                title: Response Get All Publications Publications Get
                type: array
          description: Successful Response
      summary: List all Publication IDs
  /publications/{publication_id}:
    get:
      operationId: get_publications_publications_publication_id
      parameters:
        - in: path
          name: publication_id
          required: true
          schema:
            title: Publication Id
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Publication"
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Get a specific Publication
  /studies:
    get:
      operationId: list_all_studies_studies_get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: string
                title: Response Get All Studies Studies Get
                type: array
          description: Successful Response
      summary: List all Studie IDs
  /studies/{study_id}:
    get:
      operationId: get_studies_studies_study_id
      parameters:
        - in: path
          name: study_id
          required: true
          schema:
            title: Study Id
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Study"
          description: Successful Response
        "422":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Get a specific Studie
